/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fab2f80db58e5c17a307b2c277254f92)
interface __BaseEnv_Env {
	MAIL_BUCKET: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	ADMIN_EMAIL: "steventeng2022@gmail.com";
	MAILBOX_ADDRESS: "steven@steventeng.uk";
	MAILBOX_NAME: "Steven Teng";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_EMAIL" | "MAILBOX_ADDRESS" | "MAILBOX_NAME">> {}
}
